server:
  port: 8070
spring:
  application:
    name: VCMS
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mchange.v2.c3p0.DriverManagerDataSource
    url: jdbc:mysql://localhost:3306/vcms_v2?useUnicode=true&amp&characterEncoding=utf-8&amp&serverTimezone=UTC
    username: root
    password: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mybatis/*.xml